version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ИМЯ_БД
      POSTGRES_USER: ИМЯ_ПОЛЬЗОВАТЕЛЯ
      POSTGRES_PASSWORD: ПАРОЛЬ
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgresql://ИМЯ_ПОЛЬЗОВАТЕЛЯ:ПАРОЛЬ@db/ИМЯ_БД
    restart: always
    ports:
      - "8000:80"
volumes:
  postgres_data:


